<?php
/**	op-asset-template:/404.phtml
 *
 * @genesis    2018-10-30  op-app-skeleton-2020:/404.php
 * @created    2025-06-11  op-asset-template:/404.phtml
 * @version    1.0
 * @package    op-asset-template
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	Change http status code.
http_response_code(404);

?>
<article>
	<h1>404 Not Found</h1>
	<p>This page could not be found. It may have been moved or deleted.</p>
	<img src="<?= OP()->URL('app:/img/404.png') ?>"/>
</article>

<?php if( OP()->isAdmin() ): ?>
<aside>
	<h1>For developer</h1>
	<h2>The 404 Not Found page can be replaced.</h2>
	<p>
		You can replace the 404 Not Found page.
		This file is loaded from the following path:
	</p>
	<pre><code><?= OP()->Path(__FILE__) ?></code></pre>
	<p>
		Please create a <code>404.phtml</code> file at the following path. Your custom design will be used to display the 404 page.
	</p>
	<pre><code><?= OP()->Path('asset:/layout') . OP()->Unit()->Layout()->Name() . '/template/404.phtml' ?></code></pre>
</aside>
<?php endif; ?>
