<?php
/**	op-asset-template:/t9n.phtml
 *
 * @created    2025-07-16
 * @version    1.0
 * @package    op-asset-template
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translator.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translate_Language.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/color.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/Translate_Language.css');

?>
<section data-t9n="true" data-t9n-locale="en:us">
	<p>Translation service</p>
</section>
<div id="op-translate-language-area"></div>
