<?php
/**	op-asset-template:/translation.phtml
 *
 * @created    2025-07-16
 * @version    1.0
 * @package    op-asset-template
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translator.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translate_Language.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/color.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/Translate_Language.css');
