<?php
/**	op-asset-template:/translation.phtml
 *
 * @created    2025-07-16
 * @license    Apache-2.0
 * @package    op-asset-template
 * @copyright  Tomoaki Nagahara
 */

/**	namespace
 *
 */
namespace OP;

//	...
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translator.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/js/Translate_Language.js');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/color.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/Translate_Language.css');
