<?php
/**	op-asset-template:/translation.phtml
 *
 * @created    2025-07-16
 * @license    Apache-2.0
 * @package    op-asset-template
 * @copyright  Tomoaki Nagahara
 */

/**	namespace
 *
 */
namespace OP;

//	Leave early.
if(!OP()->Config('execute')['translation'] ?? false ){
	return;
}

//	WebPack
OP()->Unit()->WebPack()->Auto(
	'asset:/webpack/js/Translator.js',
	'asset:/webpack/js/Translate_Language.js',
	'asset:/webpack/css/color.css',
	'asset:/webpack/css/Translate_Language.css',
);

?>
<!-- Translation Service -->
<div data-t9n="true" data-t9n-locale="en:us">
	<h1>Translation Service</h1>
</div>
<div id="op-translate-language-area"></div>
