<?php
/**	op-asset-template:/welcome.phtml
 *
 * @genesis    2018-10-30  op-app-skeleton-2020:/404.php
 * @created    2025-06-11  op-asset-template:/404.phtml
 * @version    1.0
 * @package    op-asset-template
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	Get layout name.
$layout = OP()->Unit()->Layout()->Name();

?>
<section data-translation="true" data-translation-locale="en:us">

<h1>Welcome to the onepiece-framework!!</h1>

<aside>
	<h1>This welcome page can be replaced</h1>
	<p>
		You can replace the 404 Not Found page.
		This file is loaded from the following path:
	</p>
	<pre><code><?= OP()->Path(__FILE__) ?></code></pre>

	<?php if( OP()->Unit()->isInstalled('layout') ): ?>
	<p>
		Please create a <code>welcome.phtml</code> file at the following path. Your custom design will be used to display the welcome page.
	</p>
	<pre><code><?= "asset:/layout/{$layout}/template/welcome.phtml" ?></code></pre>
	<?php endif; ?>

</aside>

</section>

<!-- Translation -->
<?php
if( OP()->Config('translation')['execute'] ?? false ){
	OP()->Template('translation.phtml');
}
?>
