<?php
/**	op-asset-template:/welcome.phtml
 *
 * @genesis    2018-10-30  op-app-skeleton-2020:/404.php
 * @created    2025-06-11  op-asset-template:/404.phtml
 * @license    Apache-2.0
 * @package    op-asset-template
 * @copyright  Tomoaki Nagahara
 */

/**	namespace
 *
 */
namespace OP;

//	...
if( OP()->isShell() ){
	echo PHP_EOL."Welcome to ONEPIECE Framework!!".PHP_EOL;
	return;
}

//	Get layout name.
$layout = OP()->Unit()->Layout()->Name();

?>
<!-- Introduction of the ONEPIECE Framework -->
<section data-translation="true" data-translation-locale="en:us">
	<h1>The ONEPIECE Framework is insanely great!!</h1>
	<p>
		<img src="<?= OP()->URL('app:/webpack/img/icon.png') ?>" style="float: left; margin-right: 0.5em; height: 6.5em;" />
		Welcome to the ONEPIECE Framework!!<br/>
		Was installing the ONEPIECE Framework easy?<br/>
		The ONEPIECE Framework is designed to be simple and intuitive.<br/>
		Because it’s simple and intuitive, it’s easy to understand and straightforward with no confusion.<br/>
	</p>
</section>

<!-- Introduction of the welcome page -->
<section data-translation="true" data-translation-locale="en:us">
	<h1>This welcome page can be replaced</h1>
	<p>
		You can replace the this welcome page.<br/>
		This file is loaded from the following path:
	</p>
	<pre><code><?= OP()->Path(__FILE__) ?></code></pre>

	<?php if( OP()->Unit()->isInstalled('layout') ): ?>
	<p>
		Please create a <code>welcome.phtml</code> file at the following path.<br/>
		You can display a custom welcome page.
	</p>
	<pre><code><?= "asset:/layout/{$layout}/template/welcome.phtml" ?></code></pre>
	<?php endif; ?>
</section>

<!-- Introduction of the HTML pass-through -->
<section data-translation="true">
	<h1>HTML Pass-through</h1>
	<p>
		HTML pass-through is a feature that allows HTML pages to be output directly.<br/>
		You can display a fully laid-out page without having to create empty controllers or methods.<br/>
		<a href="pass-through.html">Click here for details and to view a sample page.</a>
	</p>
</section>

<!-- Introduction of the develop page -->
<section>
	<h1 data-translation="true">You can create a developers page</h1>
	<?php if(!file_exists( OP::Path('app:/_develop/') ) ): ?>
		<div data-translation="true">
			<p>
				You run the following command in a shell environment:
			</p>
			<ol>
				<li>
					Move to the APP root directory: <br/>
					<code><?= OP()->Path('app:/') ?></code>
				</li>
				<li>
					Create an alias with the following command: <br/>
					<?php if( _ROOT_GIT_ == _ROOT_APP_ ): ?>
					<code>ln -s asset/module/develop _develop</code>
					<?php else: ?>
					<code>ln -s ../asset/module/develop _develop</code>
					<?php endif; ?>
				</li>
				<li>
					Once you've completed the above steps, reload this page.
				</li>
			</ol>
		</div>
	<?php else: ?>
		<p data-translation="true">The following link will take you to the develop page.</p>
		<div data-translation="false" class="code">
			<a href="_develop">_develop</a>
		</div>
	<?php endif; ?>
</section>

<!-- Translation Service -->
<?php if( OP()->Config('execute')['translation'] ?? false ): ?>
	<hr/>
	<section data-t9n="true" data-t9n-locale="en:us">
		<h1>Translation Service</h1>
	</section>
	<div id="op-translate-language-area"></div>
<?php endif; ?>
