<?php
/**	op-skeleton-2020:/asset/template/layout/header.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   op-skeleton-2020
 * @author    Tomoaki Nagahara
 * @copyright Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 * @creation  2019-03-01
 */
namespace OP;

//	...
if( OP::isAdmin() ){
	echo '<!-- ' . OP::Path(__FILE__) . ' -->';
}

?>
<header>
	<a href="<?= OP::URL('app:/') ?>"><?= Config::Get('app')['title'] ?? 'TOP' ?></a>
</header>
