<?php
/**	op-skeleton-2020:/asset/template/layout/header.phtml
 *
 * @creation  2018-04-12
 * @license   Apache-2.0
 * @package   op-skeleton-2020
 * @copyright Tomoaki Nagahara
 */

/**	namespace
 *
 * @creation  2019-03-01
 */
namespace OP;

//	...
if( OP::isAdmin() ){
	echo '<!-- ' . OP::Path(__FILE__) . ' -->';
}

//	...
$app   = Config::Get('app');
$top   = $app['top']   ?? OP::URL('app:/');
$title = $app['title'] ?? 'TOP';

?>
<header>
	<a href="<?= $top ?>"><?= $title ?></a>
</header>
